[versions]
agp = "8.13.0"
androidx-activity = "1.11.0"
kotlin = "2.2.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-bom = "androidx.compose:compose-bom:2025.10.01"
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }